### ISSUE TITLE
[shutdown/logout]: waits 4-5 seconds idle before continuing, even when "no confirmation" is set

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.8#9]
same when pressing the "power" button of the computer

**Comment by star-buck** [comment]
@davidedmundson : is this on purpose or what might be the cause of this?

**Comment by star-buck** [comment]
@davidedmundson : ping...

**Comment by davidedmundson** [comment]
Found it.

It tries to play a sound notificaton and waits for that to end before doing the final stage.
If that fails to finish for whatever reason,  - there's a timeout after 5 seconds to give up and continue

It's /possibly/ fixed by a commit to knotification last week. I'll test that, failing that I'll make a patch for this.

**Comment by star-buck** [comment]
seems fixed.
